@app_port = {{$dotenv APP_PORT}}

POST http://localhost:{{app_port}}/api/v1/products?t={{$timestamp}}
Content-Type: application/json
User-Agent: Aldous-Huxley-v1.0

{
  "name": "Warhammer 40K",
  "size": "M",
  "unitaryPrice": 19.9,
  "description": "Ravening aliens strike at a desperate Imperium in the new edition of Warhammer 40,000."
}

# ---

GET http://localhost:{{app_port}}/api/v1/products?page=1
Content-Type: application/json

# ---

GET http://localhost:{{app_port}}/healthcheck
